# In .github/workflows/auto-merge.yml

name: Auto Merge Release PR

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: >-
      github.event.pull_request.user.login == 'virajjayarathna' &&
      github.event.pull_request.head.ref == 'release-please--branches--main'

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Auto-merge Release PR
        uses: pascalgn/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"