name: Create Release

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    # Grant permissions for the action to create a release and write to PRs
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Run Release Please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          # This is the type of release to create. 'simple' is the most common.
          release-type: simple
          # The name of your package, used in the changelog.
          package-name: my-awesome-project